import { runGate, runSetup } from '@/gates';
import type { Issue } from '@/github';
import { loadPrompt, renderPrompt } from '@/prompt';
import { knowledgeVars, specsDevGuidance } from '@/specs';
import type { StageContext } from '@/stages/context';
import { loggedRun } from '@/stages/run';
import { PLAN_MARKER } from '@/stages/triage';

const DEV_TIMEOUT_MS = 60 * 60_000;

export async function runFix(
  ctx: StageContext,
  cwd: string,
  issue: number,
  failureOutput: string,
): Promise<void> {
  const template = await loadPrompt(ctx.promptsDirs, 'fix');
  const prompt = renderPrompt(template, { failure_output: failureOutput });
  await loggedRun(ctx, issue, 'fix', {
    prompt,
    cwd,
    model: ctx.config.models.dev,
    maxTurns: ctx.config.maxTurns.dev,
    access: 'write',
    bashAllowlist: ctx.config.devBashAllowlist,
    timeoutMs: DEV_TIMEOUT_MS,
    onProgress: (m) =>
      ctx.onEvent({ ts: Date.now(), issue, stage: 'fix', kind: 'progress', message: m }),
  });
}

/**
 * Push, and on rejection give the fix agent one shot at whatever the target
 * repo's pre-push hooks complained about, then push again. The second
 * rejection propagates — auth and diverged-branch failures must stay loud.
 */
export async function pushWithRepair(ctx: StageContext, cwd: string, issue: number): Promise<void> {
  try {
    await ctx.worktrees.push(issue);
  } catch (err) {
    const output = err instanceof Error ? err.message : String(err);
    await runFix(
      ctx,
      cwd,
      issue,
      `git push was rejected — most likely the repo's pre-push hook. Make its checks pass in this worktree.\n\n${output}`,
    );
    const gate = await runGate(ctx.exec, cwd, ctx.config.gate, ctx.platform);
    if (!gate.ok) throw new Error(`gate failed after push repair:\n${gate.output}`, { cause: err });
    // An environment-only repair (e.g. installing deps) commits nothing; the
    // retry still runs.
    await ctx.worktrees.commitAll(issue, `fix: make pre-push checks pass for #${issue}`);
    await ctx.worktrees.push(issue);
  }
}

export async function runDev(ctx: StageContext, issue: Issue): Promise<void> {
  await ctx.github.swapLabel(issue.number, 'agent:approved', 'agent:in-dev');
  const plan = await ctx.github.findComment(issue.number, PLAN_MARKER);
  if (!plan) throw new Error('no plan comment found');

  const wt = await ctx.worktrees.create(issue.number);
  if (ctx.config.setup) {
    ctx.onEvent({
      ts: Date.now(),
      issue: issue.number,
      stage: 'dev',
      kind: 'progress',
      message: `worktree setup: ${ctx.config.setup}`,
    });
    await runSetup(ctx.exec, wt.path, ctx.config.setup, ctx.platform);
  }
  const template = await loadPrompt(ctx.promptsDirs, 'dev');
  const prompt = renderPrompt(template, {
    issue_title: issue.title,
    issue_body: issue.body,
    plan,
    ...(await knowledgeVars(wt.path, specsDevGuidance)),
  });
  await loggedRun(ctx, issue.number, 'dev', {
    prompt,
    cwd: wt.path,
    model: ctx.config.models.dev,
    maxTurns: ctx.config.maxTurns.dev,
    access: 'write',
    bashAllowlist: ctx.config.devBashAllowlist,
    timeoutMs: DEV_TIMEOUT_MS,
    onProgress: (m) =>
      ctx.onEvent({
        ts: Date.now(),
        issue: issue.number,
        stage: 'dev',
        kind: 'progress',
        message: m,
      }),
  });

  let gate = await runGate(ctx.exec, wt.path, ctx.config.gate, ctx.platform);
  if (!gate.ok) {
    await runFix(ctx, wt.path, issue.number, gate.output);
    gate = await runGate(ctx.exec, wt.path, ctx.config.gate, ctx.platform);
    if (!gate.ok) throw new Error(`gate failed after repair:\n${gate.output}`);
  }

  const committed = await ctx.worktrees.commitAll(
    issue.number,
    `feat: issue #${issue.number} — ${issue.title}`,
  );
  if (!committed) throw new Error('dev stage produced no changes');
  await pushWithRepair(ctx, wt.path, issue.number);
  const prUrl = await ctx.github.createDraftPR({
    branch: wt.branch,
    base: ctx.config.baseBranch,
    title: `#${issue.number}: ${issue.title}`,
    body: `Closes #${issue.number}\n\nGenerated by cue from the approved plan on the issue.`,
  });
  await ctx.github.swapLabel(issue.number, 'agent:in-dev', 'agent:in-review');
  await ctx.notify({
    event: 'pr-opened',
    issue: issue.number,
    title: issue.title,
    repo: ctx.config.repo,
    url: prUrl || undefined,
    text: `🔀 cue: draft PR open for #${issue.number} "${issue.title}" — awaiting review and merge${prUrl ? `: ${prUrl}` : ''}`,
  });
}
