import { runGate } from '@/gates';
import type { Issue } from '@/github';
import { loadPrompt, renderPrompt } from '@/prompt';
import { knowledgeVars, specsDevGuidance } from '@/specs';
import type { StageContext } from '@/stages/context';
import { loggedRun } from '@/stages/run';
import { PLAN_MARKER } from '@/stages/triage';

const DEV_TIMEOUT_MS = 60 * 60_000;

export async function runFix(
  ctx: StageContext,
  cwd: string,
  issue: number,
  failureOutput: string,
): Promise<void> {
  const template = await loadPrompt(ctx.promptsDirs, 'fix');
  const prompt = renderPrompt(template, { failure_output: failureOutput });
  await loggedRun(ctx, issue, 'fix', {
    prompt,
    cwd,
    model: ctx.config.models.dev,
    maxTurns: ctx.config.maxTurns.dev,
    access: 'write',
    bashAllowlist: ctx.config.devBashAllowlist,
    timeoutMs: DEV_TIMEOUT_MS,
    onProgress: (m) =>
      ctx.onEvent({ ts: Date.now(), issue, stage: 'fix', kind: 'progress', message: m }),
  });
}

export async function runDev(ctx: StageContext, issue: Issue): Promise<void> {
  await ctx.github.swapLabel(issue.number, 'agent:approved', 'agent:in-dev');
  const plan = await ctx.github.findComment(issue.number, PLAN_MARKER);
  if (!plan) throw new Error('no plan comment found');

  const wt = await ctx.worktrees.create(issue.number);
  const template = await loadPrompt(ctx.promptsDirs, 'dev');
  const prompt = renderPrompt(template, {
    issue_title: issue.title,
    issue_body: issue.body,
    plan,
    ...(await knowledgeVars(wt.path, specsDevGuidance)),
  });
  await loggedRun(ctx, issue.number, 'dev', {
    prompt,
    cwd: wt.path,
    model: ctx.config.models.dev,
    maxTurns: ctx.config.maxTurns.dev,
    access: 'write',
    bashAllowlist: ctx.config.devBashAllowlist,
    timeoutMs: DEV_TIMEOUT_MS,
    onProgress: (m) =>
      ctx.onEvent({
        ts: Date.now(),
        issue: issue.number,
        stage: 'dev',
        kind: 'progress',
        message: m,
      }),
  });

  let gate = await runGate(ctx.exec, wt.path, ctx.config.gate, ctx.platform);
  if (!gate.ok) {
    await runFix(ctx, wt.path, issue.number, gate.output);
    gate = await runGate(ctx.exec, wt.path, ctx.config.gate, ctx.platform);
    if (!gate.ok) throw new Error(`gate failed after repair:\n${gate.output}`);
  }

  const committed = await ctx.worktrees.commitAll(
    issue.number,
    `feat: issue #${issue.number} — ${issue.title}`,
  );
  if (!committed) throw new Error('dev stage produced no changes');
  await ctx.worktrees.push(issue.number);
  const prUrl = await ctx.github.createDraftPR({
    branch: wt.branch,
    base: ctx.config.baseBranch,
    title: `#${issue.number}: ${issue.title}`,
    body: `Closes #${issue.number}\n\nGenerated by cue from the approved plan on the issue.`,
  });
  await ctx.github.swapLabel(issue.number, 'agent:in-dev', 'agent:in-review');
  await ctx.notify({
    event: 'pr-opened',
    issue: issue.number,
    title: issue.title,
    repo: ctx.config.repo,
    url: prUrl || undefined,
    text: `🔀 cue: draft PR open for #${issue.number} "${issue.title}" — awaiting review and merge${prUrl ? `: ${prUrl}` : ''}`,
  });
}
