import type { ConductorConfig } from "../config";
import { runGate } from "../gates";
import type { Issue } from "../github";
import { loadPrompt, renderPrompt } from "../prompt";
import type { StageContext } from "./context";
import { PLAN_MARKER } from "./triage";

const DEV_CORE_TOOLS = ["Read", "Grep", "Glob", "Write", "Edit"];

// Bash is unrestricted unless the project scopes it via devBashAllowlist.
export function devTools(config: ConductorConfig): string[] {
  if (!config.devBashAllowlist) return [...DEV_CORE_TOOLS, "Bash"];
  return [...DEV_CORE_TOOLS, ...config.devBashAllowlist.map((p) => `Bash(${p})`)];
}

const DEV_TIMEOUT_MS = 60 * 60_000;

async function runFix(
  ctx: StageContext,
  cwd: string,
  issue: number,
  failureOutput: string,
): Promise<void> {
  const template = await loadPrompt(ctx.promptsDirs, "fix");
  const prompt = renderPrompt(template, { failure_output: failureOutput });
  const start = Date.now();
  const res = await ctx.adapter.run({
    prompt,
    cwd,
    model: ctx.config.models.dev,
    maxTurns: ctx.config.maxTurns.dev,
    allowedTools: devTools(ctx.config),
    timeoutMs: DEV_TIMEOUT_MS,
    onProgress: (m) =>
      ctx.onEvent({ ts: Date.now(), issue, stage: "fix", kind: "progress", message: m }),
  });
  await ctx.logger.log(issue, "fix", {
    prompt,
    result: res.raw,
    costUsd: res.costUsd,
    durationMs: Date.now() - start,
    outcome: "ok",
  });
}

export async function runDev(ctx: StageContext, issue: Issue): Promise<void> {
  await ctx.github.swapLabel(issue.number, "agent:approved", "agent:in-dev");
  const plan = await ctx.github.findComment(issue.number, PLAN_MARKER);
  if (!plan) throw new Error("no plan comment found");

  const wt = await ctx.worktrees.create(issue.number);
  const template = await loadPrompt(ctx.promptsDirs, "dev");
  const prompt = renderPrompt(template, { issue_title: issue.title, issue_body: issue.body, plan });
  const start = Date.now();
  const res = await ctx.adapter.run({
    prompt,
    cwd: wt.path,
    model: ctx.config.models.dev,
    maxTurns: ctx.config.maxTurns.dev,
    allowedTools: devTools(ctx.config),
    timeoutMs: DEV_TIMEOUT_MS,
    onProgress: (m) =>
      ctx.onEvent({
        ts: Date.now(),
        issue: issue.number,
        stage: "dev",
        kind: "progress",
        message: m,
      }),
  });
  await ctx.logger.log(issue.number, "dev", {
    prompt,
    result: res.raw,
    costUsd: res.costUsd,
    durationMs: Date.now() - start,
    outcome: "ok",
  });

  let gate = await runGate(ctx.exec, wt.path, ctx.config.gate);
  if (!gate.ok) {
    await runFix(ctx, wt.path, issue.number, gate.output);
    gate = await runGate(ctx.exec, wt.path, ctx.config.gate);
    if (!gate.ok) throw new Error(`gate failed after repair:\n${gate.output}`);
  }

  const committed = await ctx.worktrees.commitAll(
    issue.number,
    `feat: issue #${issue.number} — ${issue.title}`,
  );
  if (!committed) throw new Error("dev stage produced no changes");
  await ctx.worktrees.push(issue.number);
  await ctx.github.createDraftPR({
    branch: wt.branch,
    base: ctx.config.baseBranch,
    title: `#${issue.number}: ${issue.title}`,
    body: `Closes #${issue.number}\n\nGenerated by conductor from the approved plan on the issue.`,
  });
  await ctx.github.swapLabel(issue.number, "agent:in-dev", "agent:in-review");
}
