#!/usr/bin/env bun
/**
 * Regenerate src/ui-manifest.g.ts with embedded-file imports for every asset
 * in ui/build/client, so `bun build --compile` bundles the dashboard into the
 * binary. Run by scripts/build-binaries.sh; the result is NOT committed.
 */
import { readdir } from "node:fs/promises";
import { join } from "node:path";

const CLIENT_DIR = "ui/build/client";
const OUT = "src/ui-manifest.g.ts";

async function walk(dir: string, prefix = ""): Promise<string[]> {
  const out: string[] = [];
  for (const entry of (await readdir(dir, { withFileTypes: true })).toSorted((a, b) =>
    a.name.localeCompare(b.name),
  )) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) out.push(...(await walk(join(dir, entry.name), rel)));
    else out.push(rel);
  }
  return out;
}

let files: string[];
try {
  files = await walk(CLIENT_DIR);
} catch {
  console.error(`${CLIENT_DIR} not found — run \`bun run ui:build\` first`);
  process.exit(1);
}

const imports = files
  .map((f, i) => `import f${i} from "../${CLIENT_DIR}/${f}" with { type: "file" };`)
  .join("\n");
const entries = files.map((f, i) => `  "/${f}": f${i},`).join("\n");

await Bun.write(
  OUT,
  `// GENERATED by scripts/embed-ui.ts — do not commit this version.\n${imports}\n\nexport const UI_FILES: Record<string, string> = {\n${entries}\n};\n`,
);
console.log(`wrote ${OUT} with ${files.length} embedded assets`);
